### ISSUE TITLE
Wont Connect

### ISSUE THREAD

**Issue by sirprintsalot8** [AstroPrint/OctoPrint-AstroPrint#57] opened 2019-02-11 20:54 UTC
I had the Astroprint Plugin working for about a month and then it stopped. I regenerated a code and input it and it wont see the printer and still shows the octoprint as authorized user back from the last date it work. I deleted both authorized user and readded them and the same thing. My android app goes to todays date when I redo it though. I then when into Octoprint and deleted the plugin and reinstalled. The results were the same. Sorry if I am missing something but I am at a loss.

**Comment by CoDanny** [comment] 2019-02-11 21:15
I'm lost as to how the Android app and the plugin are related, also what code was regenerated? and which authorized user? octoprint's or astroprint account?

Basically I'm not sure what the problem is by this description. Could you add some screenshots perhaps?

**Comment by sirprintsalot8** [comment] 2019-02-12 12:46
A full break down. On the Android app I cant see anything. So when I go to the Astroprint tab on Octoprint it just has to add an access key. That is the code I had regenerated and entered back in. But in the Astroprint page in the settings it has authorized users under the My Applications. My phone updates when I open the astroprint app but the octoprint plugin last access is still showing back in November when it stopped working.


![screenshot 2019-02-12 07 40 24](https://user-images.githubusercontent.com/42078339/52636286-31642a00-2e9a-11e9-83d0-a5c23175214a.png)
![screenshot 2019-02-12 07 41 06](https://user-images.githubusercontent.com/42078339/52636304-3aed9200-2e9a-11e9-8c8f-d274655565b5.png)
![screenshot 2019-02-12 07 40 46](https://user-images.githubusercontent.com/42078339/52636305-3aed9200-2e9a-11e9-880a-8bb12904c8ba.png)

**Comment by CoDanny** [comment] 2019-02-14 10:12
What happens when you enter the new access key and go through the auth flow?

**Comment by sirprintsalot8** [comment] 2019-02-14 22:33
I just regenerated the key and entered it. It goes to a page asking if I want to proceed. After I hit yes it refreshes and takes me back to the main Octoprint tab.

**Comment by CoDanny** [comment] 2019-02-15 09:21
Does it ask you the key again?

**Comment by sirprintsalot8** [comment] 2019-02-15 21:16
If I go back to the tab for the Astroprint plugin it looks like the screen shot from above.

**Comment by CoDanny** [comment] 2019-02-17 08:14
ugh! Ok. This is a problem that we have been chasing for a while but haven't been able to reproduce here. Could you post here a list of all the plugins you have installed and the version of OctoPrint? We'll try to reproduce your environment.

**Comment by sirprintsalot8** [comment] 2019-02-18 17:11
Plugins:

Action Command Prompt
AstroPrint
Bed Leveling Wizard
Bed Visualizer
Cancel Objects
Cost Estimation
Cost Plugin
CuraEngine (<= 15.04)
DeleteAfterPrint Plugin
DisplayLayerProgress Plugin
Fan Speed Control
GcodeEditor
Heater Timeout
MyMiniFactory
Navbar Temperature Plugin
OctoPrint Anywhere
Octolapse
PolarCloud
Print History Plugin
PrintTimeGenius Plugin
Printer Stats
Simple Emergency Stop
TP-Link Smartplug
Tab Order
Themeify
TouchUI

**Comment by flyingelephant19** [comment] 2019-02-21 06:55
i get the same issue. well everytime i shutdown the PI and restart, the creditials are gone and have to re enter and on one of my PI's i am running the latest 0.16 octopi.

**Comment by CoDanny** [comment] 2019-08-11 09:11
This should be resolved with #65

**Closed as completed by CoDanny** 2019-08-11 09:11 UTC
